### PR TITLE
Add support for distro specific site restore callbacks

### PR DESCRIPTION
**Pull request by skodak**
Hi Marina, here is another more neutral patch adding support for custom site restore callbacks.

This is an example of the new \core\distribution class:

```

namespace core;

final class distribution {    
    /**
     * Callback for site restore/migration executed after each database table.
     *
     * @param string $tablename
     * @return void
     */
    public static function tool_vault_after_table_restore(string $tablename): void {
        global $DB;

        if ($tablename !== 'context') {
            return;
        }

        $dbman = $DB->get_manager();

        $table = new \xmldb_table('context');
        $field = new \xmldb_field('tenantid', XMLDB_TYPE_INTEGER, '10', null, null, null, null);
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
            $index = new \xmldb_index('tenantid', XMLDB_INDEX_NOTUNIQUE, ['tenantid']);
            $dbman->add_index($table, $index);
        }
    }
}

```

### CODE REVIEW

**Comment by lmscloud-io** [comment]
Thank you, I think it's much cleaner :)

I am adding this change (at the same line)
```
// Distribution callback if present.
component_class_callback('core\distribution', 'tool_vault_after_table_restore', [$tablename, $this]);
```

- it is more compact and does exactly the same as your code
- it also passes an instance of the `site_restore` class that you can use to add to the logs:

```
namespace core;

class distribution {
    public static function tool_vault_after_table_restore(string $tablename, $logger): void {
        $logger->add_to_log('!!! After table '.$tablename);
    }
}
```

is this ok with you?

**Comment by marinaglancy** [comment]
btw, it was me. I forgot to switch the account :)

**Comment by skodak** [comment]
looks ok to me, thanks

**Comment by lmscloud-io** [comment]
Added to v2.6 , thanks

**Pull request closed without merging**
